import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/header";
import MainContent from "@/components/common/main-content";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <MainContent>{children}</MainContent>
      </body>
    </html>
  );
}
